### ISSUE TITLE
missing DreamSDK-R3 

### ISSUE THREAD

**Issue by ozzyyzzo4096** [dreamsdk/dreamsdk#1]
keep up the good work ;-)

**Comment by sizious** [comment]
Hello!
Thank you for your interest! Indeed, this repository was made for storing DreamSDK packages (i.e. the same packages published on the [website](https://dreamsdk.org/)). The R3 isn't ready yet but you can grab a public test version from [Discord](https://discord.com/channels/488332893324836864/755840673780990165).
Cheers!

**Comment by sizious** [comment]
Hello,
DreamSDK R3 is now officially available!
[You may click here to grab it.](https://github.com/dreamsdk/dreamsdk/releases/tag/r3-3.0.4.2311)
Cheers!
