### ISSUE TITLE
KallistiOS Ports fail to download over SSL (DreamSDK-R2)

### ISSUE THREAD

**Issue by portalsam1** [dreamsdk/dreamsdk#2]
Some KOS Ports will refuse to download with the error 

> OpenSSL: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
Unable to establish SSL connection.

![image](https://user-images.githubusercontent.com/41414314/189552453-55e0ea66-0ff4-46b9-a3bf-2e67d2533bec.png)

![image](https://user-images.githubusercontent.com/41414314/189552513-dea51337-98a0-45fa-b968-1905237c342c.png)

My openSSL version is up to date so I don't know which tool is causing this fault or if this hasn't been updated recently.
Is there a newer version of this tool?

**Comment by sizious** [comment]
Indeed, this has been fixed in the (not yet released) DreamSDK R3. It will be released soon, stay tuned. 👍🏻

**Comment by sizious** [comment]
Hello 👋🏻 
You may find a R3-dev package here:
https://discord.com/channels/488332893324836864/755840673780990165/1053736527672385597
Don’t hesitate to test this package and report any issue 😀

**Comment by sizious** [comment]
Hello,
DreamSDK R3 is now officially available!
[You may click here to download it.](https://github.com/dreamsdk/dreamsdk/releases/tag/r3-3.0.4.2311)
Cheers!
