### ISSUE TITLE
sh-elf-gdb.exe error

### ISSUE THREAD

**Issue by ReyingRexer** [dreamsdk/dreamsdk#3]
during the kallisti os install, this error would pop up every time, any fix?

![image](https://github.com/dreamsdk/dreamsdk/assets/92257438/271d4333-1318-4d80-b46f-699c68af7729)

**Comment by sizious** [comment]
Hello,
Thank you for your message,
What version are you using?
Are you using the latest R3 from Discord?

**Comment by sizious** [comment]
You may find it here:
https://discord.com/channels/488332893324836864/755840673780990165/1147314607065665577
